apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: pacman-secret
  namespace: pacman
spec:
  encryptedData:
    pass: AgCQfVUSlTGrEy6yN2IVCV9yiz1zTKzAQrc070mXwkl6hHlYUDlabXZumwQuf6BfChkLEjj/Ist10FYceVwicJNMT5AL0Ln5N+ZFgjMPw2b8NNJv0LslSYDSP1mO4iYhfgjMYGZjREeEth3t5vwddU7i8EfnMQLaVCs8gOlV4+3HJp4TUAe2QXBvrVotZKGwqow4aIqdBacuSDjFhVaPft8HCT9FVD+kcyIHaLlyjaUC/qrytjTEa3q9RpeCVdgQnCICdYFO4+LRZe3haWzdCrgAG6r7zMdoAV0mCDStIbpq5GheHMLwKp2H342RQRZYeGvs+oR8Wm0KrJBREcBz2kKDfSTDFQ5C+ORAVbFtAj3jhrAOMFpo7EWTjWMLTUzM045OAgzkZ6tywGvDQydjCFZmjErUaq+5gxHaMHi8os+6cqg8iVDiIucsUF5s8DplS/37xcDE38NM1xclQidQwY/aqYWEnsc851cBUaCI7gtDiGZAcKWlQS0/+85gpFKYCnMLFuYxFNJjZXSJBjVOrGCrZRYiTg5WdjtnBDdq3w9E0a9zL7Cyv2jzJyDPsQYW7QYZFWxiR1AIC7VgsDrdQtMUbWHfJOi0UiuHTkQ8BXxCtsYngMVNZeQUHQ7Tz7U1kC/gztdyUbzCftCP6+FzK17Jes7zevOmyd8bCYfwX/n4C7BdRp0sM8BdnXyE0eWEQU7FD4hsjcY=
    user: AgDhppIqfnAO6Eo+WDcPnaJATlNkgaZAVP8CHM403ST3WPm1sv2jVVvix8pfr3Ft1+XiaLvSXSxMDV8mNQ9zwNPlgeqEG7pxIBnSU9qJDhGs7ogDUQURL2HinBREzA9ejavfgQTkljozoLapP4UtkFnUmpKY2SIUqPzpp7s18bZTrW8TLPZge+eOlSJDzf6yCDhFyS1gmXnez1Lerq7VrKIKhtENtjQwS2fxHBPrB/asKEl+goms4jc+dEplabhM+ninV0kPFLH3vw9siDR5syjORykNMIKDPZzXrCKG0okRzzkwnQHlVcUIlPFbAP6gKDc7oi0+YibMw+Us/UAQVa0/n3GEtF1tgjueDO4UI0dyg9gtj2KdcB0yQnGnxDO4I9zH216kILLmcLtmRtmYCpbk8e0EB8CZgvtBxX4LZ6hf1qp8LuvrnSoiDatAEqV4tVvqmQJs35CCyjTv1fpQ5DVgpX1Bx1lJJe87UTM9WWDIEXLSUjfusMKeckfVyANQ5jh+3jn2f+ujKzSjqlzPhfDIW36n4PpUo5i6Mn0L2wcFhEEnztsXEWDTYVrf5zrZ/87HLZjDUTpw6Mp/vb4FDV+/Omig746uVxzBB90h6ImbvTeIv5e2NcMWgI5i/+eTBfcUurqyAUOtqJQRuo5Ts3kQr4bmlFFD8G09Adz9OUfIqkQGf3sMATFLEC508XOLly9NWC+WgQ0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      managedFields:
        - apiVersion: v1
          fieldsType: FieldsV1
          fieldsV1:
            f:data:
              .: {}
              f:pass: {}
              f:user: {}
            f:type: {}
          manager: kubectl
          operation: Update
          time: "2025-01-23T12:20:37Z"
      name: pacman-secret
      namespace: pacman
    type: Opaque